### PR TITLE
Ability to DELETE Product from Feed by SKU

### PR DESCRIPTION
**Pull request by scottlaurent**

### CODE REVIEW

**Comment by mabuak** [comment]
Hi @scottlaurent, will be better if you can add that with multiple product sku...

**Comment by Elompenta** [comment]
@scottlaurent great work. Are you able to extend your solution that we can put multiple SKUs to your method?

thanks for your work!

**Comment by Elompenta** [comment]
@meertensm 
Dont know how to update an existing pull request and make a new commit.
It is possible?

@meertensm @scottlaurent 
I have have created a new Pull request - https://github.com/meertensm/amazon-mws/pull/50

**Comment by Elompenta** [comment]
can be clsoed - already merged in https://github.com/meertensm/amazon-mws/pull/50

**Pull request closed without merging**
